manifest:
  defaults: 
      revision: v0.3 

  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk-adaptive-key
      remote: urob
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

  self:
    path: config

